// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/issue-snooze/snooze-bot/cmd"
)

var _ Cmd = (*Run)(nil)

type Run struct {
	*RootCmd
	Flags         *flag.FlagSet
	config        string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Run) error
}

type UsageDataRun struct {
	*Run
	Recursive bool
}

func (c *Run) Usage() {
	err := executeUsage(os.Stderr, "run_usage.txt", UsageDataRun{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Run) UsageRecursive() {
	err := executeUsage(os.Stderr, "run_usage.txt", UsageDataRun{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Run) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "config":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				c.config = value
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if char == "c" {
					found = true
					// Value flag
					value := ""
					if j+1 < len(shorts) {
						// Value is the rest of the short flag
						value = shorts[j+1:]
						if strings.HasPrefix(value, "=") {
							value = value[1:]
						}
						j = len(shorts) // break inner loop
					} else {
						// Value is the next arg
						if i+1 < len(args) {
							value = args[i+1]
							i++
						} else {
							return fmt.Errorf("flag -%s requires a value", char)
						}
					}
					c.config = value
				}
				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("run failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewRun() *Run {
	set := flag.NewFlagSet("run", flag.ContinueOnError)
	v := &Run{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.StringVar(&v.config, "config", "", "The path to the config file (optional)")
	set.StringVar(&v.config, "c", "", "The path to the config file (optional)")
	set.Usage = v.Usage

	v.CommandAction = func(c *Run) error {

		cmd.RunBot(c.config)
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
